import { Link } from "react-router-dom";
import { BrandMark, Icon } from "../../components/Icon";
import { InstallButton } from "../../pwa/PwaControls";
export function AboutPage() {
  return <div className="page about-page">
    <section className="about-hero"><BrandMark/><p className="eyebrow">MEET OPEN SOCIAL</p><h1>Your people.<br/>Your posts.<br/><span>Yours.</span></h1><p>Social media should connect you to people.<br/>It shouldn’t tie you to one company.</p><Link to="/" className="btn btn-primary">Explore Open Social <Icon name="arrow"/></Link></section>
    <section className="about-section"><span className="eyebrow">THE BIG IDEA</span><h2>A social network you can take with you.</h2><p>Today, your profile and your audience usually belong to the app you use. Move somewhere else, and you start again.</p><p>Open Social gives compatible apps a shared way to handle accounts, posts, and connections. That shared set of rules is the <strong>protocol</strong>. Think of email: different apps, one way to stay in touch.</p></section>
    <div className="about-grid"><section className="card"><span className="feature-icon"><Icon name="profile"/></span><h2>One identity. Your keys.</h2><p>Your account is controlled by keys you keep. A website gives you a way to use it; it doesn’t own your identity. Back up your account so you can recover it.</p></section><section className="card"><span className="feature-icon"><Icon name="people"/></span><h2>Connections that travel.</h2><p>Compatible apps can use the same account and connections. You don’t have to rebuild your circle just because you prefer a different app.</p></section><section className="card"><span className="feature-icon"><Icon name="lock"/></span><h2>Choose your audience.</h2><p>Public posts are for everyone. Friends-only posts are encrypted so the people you share keys with can read them.</p></section><section className="card"><span className="feature-icon"><Icon name="layers"/></span><h2>Room for better apps.</h2><p>Anyone can build tools for the protocol. Different designs and features can serve the same community.</p></section></div>
    <section className="about-section"><span className="eyebrow">TWO WAYS IN</span><h2>The website and plugin are your tools.</h2><div className="tool-explainer"><Icon name="globe" size={28}/><div><h3>The website</h3><p>Your home for reading, posting, finding friends, and messaging. Install it as an app to open it from your home screen.</p></div></div><div className="tool-explainer"><Icon name="layers" size={28}/><div><h3>The browser plugin</h3><p>Bring Open Social into supported sites such as Facebook. See Open Social posts in the feed and choose to publish to Open Social while you’re there.</p></div></div><p>Both use the same protocol. Your Open Social account and connections don’t disappear just because one website or plugin stops working. You can use another compatible tool.</p><p className="muted">The plugin doesn’t move your Facebook friends or posts automatically, and it doesn’t control Facebook. You choose what you share with Open Social.</p></section>
    <section className="card about-honesty"><Icon name="shield" size={28}/><div><h2>Open doesn’t mean magic.</h2><p>Removing a friend stops sharing access to future friends-only posts. It can’t take back keys or posts they already received. Add them again and, once your unlocked apps sync, both of you can read each other’s friends-only posts again.</p><p>Public information is public, and other people can keep copies of what they see. Apps and storage services still need to be available to display content.</p><p>The protocol records account and sharing rules on Koinos, a shared network independent apps can read. Open Social currently runs on its test network while we build and improve it.</p></div></section>
    <section className="about-cta"><h2>Make yourself at home.</h2><p>Find your people. Share something worth sharing.</p><div className="row"><Link to="/people" className="btn btn-primary">Find people <Icon name="arrow"/></Link><InstallButton/></div></section>
  </div>;
}
