import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { MemoryRouter } from "react-router-dom";
import { afterEach, expect, it, vi } from "vitest";
import { IndexerClient, type ProfileSummary } from "../../api/indexer";
import { buildProfileDocument } from "../../api/profiles";
import { ServicesProvider } from "../../api/services";
import { PeopleSearch } from "./PeopleSearch";
let root: Root;
let box: HTMLDivElement;
afterEach(async () => { await act(async () => root?.unmount()); box?.remove(); vi.useRealTimers(); });
it("ignores late results for an old query and links the new nickname to the correct account", async () => {
  vi.useFakeTimers();
  let finishOld: (response: Response) => void = () => {};
  const old = new Promise<Response>(resolve => { finishOld = resolve; });
  const person = (name: string): ProfileSummary => ({ account: `1${name}`, owner: "", profileUri: buildProfileDocument({ display_name: name }).uri, encryptionKey: "", profileHash: "", keyVersion: 1, registeredAt: "0", updatedAt: "0" });
  const response = (name: string) => new Response(JSON.stringify({ items: [person(name)] }));
  const client = new IndexerClient({ baseUrl: "https://test.invalid", fetch: async url => url.includes("query=Old") ? old : response("New") });
  box = document.createElement("div"); document.body.append(box); root = createRoot(box);
  const factory = (resolved: import("../../stores/settings").ResolvedSettings) => ({ resolved, indexer: client });
  await act(async () => root.render(<MemoryRouter><ServicesProvider factory={factory}><PeopleSearch initialQuery="Old"/></ServicesProvider></MemoryRouter>));
  await act(async () => vi.advanceTimersByTimeAsync(300));
  const input = box.querySelector("input")!;
  await act(async () => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")!.set!.call(input, "New"); input.dispatchEvent(new Event("input", { bubbles: true })); });
  await act(async () => vi.advanceTimersByTimeAsync(300));
  expect(box.querySelector("a")?.getAttribute("href")).toBe("/u/1New");
  await act(async () => { finishOld(response("Old")); });
  expect(box.querySelector("a")?.getAttribute("href")).toBe("/u/1New");
  expect(box.textContent).not.toContain("1Old");
});
