/** Offline resource simulation; not price, farming-resistance, or Mana-cost evidence. */
import { account, at, FULL, RECHARGE_BLOCKS, summary, useActions, useVoteWeight } from "../research/token-v2/model.js";

const DAY = RECHARGE_BLOCKS / 5n;
const decimal = (ticks: bigint) => (Number(ticks) / Number(FULL)).toFixed(4);

console.log("# Token v2 resource simulation\n");
console.log("Generated by `npm run simulate:token-v2`. Deterministic reference-model results only; no chain calls.\n");
console.log("One action costs one full unit. Each used unit recharges one internal tick/block, up to 144,000 ticks. A modeled day is 28,800 blocks. Real elapsed time is approximate.\n");
console.log("## Free allowance comparison\n");
console.log("Each run lasts 30 modeled days. Burst traffic submits the entire daily request at the day's first block. Even traffic distributes requests through the day. Rejected attempts consume no capacity.\n");
console.log("| Free units | Requests/day | Pattern | Accepted / attempted | Accepted on day 30 | Maximum stored cohorts |");
console.log("| ---: | ---: | --- | ---: | ---: | ---: |");
for (const free of [25n, 50n, 100n]) {
  for (const requested of [5, 20, 100]) {
    for (const pattern of ["even", "burst"]) {
      let a = account("simulation", 0n, free);
      let accepted = 0, finalDay = 0, groups = 1;
      for (let day = 0; day < 30; day++) {
        for (let action = 0; action < requested; action++) {
          const block = BigInt(day) * DAY + (pattern === "even" ? BigInt(action) * DAY / BigInt(requested) : 0n);
          if (summary(a, block).availableActions >= 1n) {
            a = useActions(a, block);
            accepted++;
            if (day === 29) finalDay++;
          } else a = at(a, block);
          groups = Math.max(groups, a.free.length);
        }
      }
      console.log(`| ${free} | ${requested} | ${pattern} | ${accepted} / ${30 * requested} | ${finalDay} | ${groups} |`);
    }
  }
}

console.log("\n## Idle holdings do not accelerate recovery\n");
console.log("One paid action at block zero, no free allowance and no later activity.\n");
console.log("| Holdings | Depleted units | Recovered after one modeled day | Locked at day one |");
console.log("| ---: | ---: | ---: | ---: |");
for (const balance of [1n, 100n, 1000n, 1_000_000n]) {
  const s = summary(useActions(account("holder", balance, 0n), 0n), DAY);
  console.log(`| ${balance} | 1 | ${decimal(s.tokenCapacity - (balance - 1n) * FULL)} | ${s.locked} |`);
}

console.log("\n## Shared activity and voting\n");
const used = useActions(account("shared", 100n, 0n), 0n, 40n);
const voted = useVoteWeight(used, 0n, 60n);
console.log(`100 paid units, no free allowance: 40 actions leave ${summary(used).availableVoteWeight} available vote weight. Consuming that weight leaves ${summary(voted).availableActions} actions and ${summary(voted).transferable} transferable tokens. After one modeled day, ${summary(voted, DAY).availableActions} action credits recover; they can instead fund the same amount of voting weight.\n`);
console.log("## Interpretation and limits\n");
console.log("- Keep 100 free units as the comparison baseline; no allowance reduction is selected by this report.");
console.log("- 25 or 50 free units visibly constrain ordinary 20-action/day traffic. Action pricing and target user journeys must be decided before reducing the allowance.");
console.log("- These results measure resource accounting, not independent users, sustainable sponsor funding, transaction RC, reward fairness, capital concentration, or advertising effectiveness.");
console.log("- Fully used tokens remain nontransferable until individually full, even when their recovered fractions add up to spendable actions.");
console.log("- Cohort counts in these traces are not a worst-case on-chain bound. Storage growth, execution bounds and adversarial histories remain contract-port gates.");
