import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { Contract, Signer, type OperationJson } from "koilib";
import { ABIS } from "@osp/proto";
import { ProtocolClient, identityFromSeed, loadDeployment, encryptContent, contentHash, postId as computePostId, type Identity } from "@osp/sdk";
import { contractSigner, deployerSigner, networkFromArgs, parseArgs, providerFor, readDeployment, readContractArtifacts, requireSeed } from "./common.ts";
import { submitMeasured } from "./deployment-transactions.ts";
const args=parseArgs(process.argv.slice(2)),{name:network,preset}=networkFromArgs(args);
assert.equal(network,"harbinger"); assert(args.execute,"Explicit --execute is required");
assert(typeof args.evidence==="string","--evidence path is required (public receipts only)");
const provider=providerFor(preset),deployer=deployerSigner(preset,provider),deployment=loadDeployment(readDeployment(network));
assert.equal(await provider.getChainId(),deployment.chainId);
// New isolated account per run: no reset of somebody else's rehearsal or production state.
const run=typeof args.run==="string"?args.run:randomBytes(8).toString("hex");
assert(/^[a-zA-Z0-9_-]{1,80}$/.test(run));
const owner=contractSigner(network,`token-economy-rehearsal-${run}`,requireSeed(),provider);
assert.notEqual(owner.getAddress(),deployment.contracts.token.address);
const art=readContractArtifacts("token");
const token=new Contract({id:owner.getAddress(),abi:ABIS.token as never,provider,signer:owner,bytecode:art.wasm,options:{payer:deployer.getAddress()}});
const evidence:{run:string;contract:string;wasmSha256:string;started:string;checks:Array<{name:string;txId?:string;block?:number;rc?:string}>;policy?:unknown;finished?:string}={run,contract:owner.getAddress(),wasmSha256:art.wasmSha256,started:new Date().toISOString(),checks:[]};
const save=()=>{mkdirSync(dirname(String(args.evidence)),{recursive:true});writeFileSync(String(args.evidence),JSON.stringify(evidence,null,2)+"\n");};
const check=(name:string)=>{evidence.checks.push({name});console.log(`PASS ${name}`);save();};
const client=new ProtocolClient({rpc:provider,deployment:{...deployment,contracts:{...deployment.contracts,token:{...deployment.contracts.token,address:owner.getAddress()}}}});
const send=async(name:string,operations:OperationJson[],signer:Signer)=>{
  const prepared=await client.prepare(operations,{payer:deployer.getAddress(),payee:signer.getAddress()});
  const result=await submitMeasured(prepared,provider,[signer,deployer],{log:m=>console.log(`[${name}] ${m}`)});
  const block=await result.transaction.wait("byTransactionId",120000);
  evidence.checks.push({name,txId:result.transaction.id,block:block.blockNumber,rc:result.receipt.rc_used});
  console.log(`PASS ${name}: ${result.transaction.id}`);save();return result;
};
const refuse=async(name:string,operations:OperationJson[],signer:Signer,pattern:RegExp)=>{
  const prepared=await client.prepare(operations,{payer:deployer.getAddress(),payee:signer.getAddress()});
  await assert.rejects(submitMeasured(prepared,provider,[signer,deployer],{dryRun:true}),pattern);check(name);
};
const read=async(method:string,input:Record<string,unknown>={})=>(await token.functions[method]!(input)).result as any;
const head=async()=>BigInt((await provider.getHeadInfo()).head_topology!.height!);
const waitBlock=async(target:bigint)=>{
  const deadline=Date.now()+10*60_000;
  while(await head()<target){assert(Date.now()<deadline,"testnet block wait timed out");console.log(`Waiting for rehearsal settlement at block ${target}`);await new Promise(r=>setTimeout(r,15000));}
};
try{
  const upload=await token.deploy({abi:art.abi,sendTransaction:false,signTransaction:false});
  const deployed=await submitMeasured(upload.transaction!,provider,[owner,deployer],{log:console.log});
  await deployed.transaction.wait("byTransactionId",120000);
  evidence.checks.push({name:"isolated-code-upload",txId:deployed.transaction.id,rc:deployed.receipt.rc_used});save();
  const deps=Object.fromEntries(["identity","relationships","publications","messaging"].map(n=>[n,deployment.contracts[n as keyof typeof deployment.contracts].address]));
  await send("init",[await client.ops.token.init(deps as never)],owner);
  const accounts=[identityFromSeed(randomBytes(32)),identityFromSeed(randomBytes(32)),identityFromSeed(randomBytes(32))];
  const [a,b,c]=accounts as [Identity,Identity,Identity];
  for(const [i,me] of accounts.entries()) await send(`register-${i}`,[await client.ops.identity.register({account:me.account,encryption_key:me.encryption.publicKey,key_version:1})],me.signer);
  const post=async(me:Identity,sequence:string)=>{
    const envelope=encryptContent({content:{version:1,text:`Isolated token economy rehearsal ${run}/${sequence}`,mime:"text/plain"}}).bytes,hash=contentHash(envelope);
    const id=computePostId({chainId:deployment.chainId,protocolVersion:1,author:me.account,sequence,contentHash:hash});
    await send(`publish-${sequence}`,[await client.ops.publications.publish({author:me.account,post_id:id,sequence,audience:0,envelope,content_hash:hash,idempotency_key:randomBytes(16)})],me.signer);
    return {id,hash};
  };
  const first=await post(b,"1"),second=await post(b,"2");
  const unfunded=identityFromSeed(randomBytes(32));
  await send("register-with-no-voting-tokens",[await client.ops.identity.register({account:unfunded.account,encryption_key:unfunded.encryption.publicKey,key_version:1})],unfunded.signer);
  await send("activate-short-rehearsal-period",[await client.ops.token.activate_economy({test_period_blocks:"60"})],owner);
  for(const [i,me] of accounts.entries()) await send(`grant-${i}`,[await client.ops.token.grant_test_tokens({account:me.account,value:"20"})],owner);
  const policy=await read("get_economy");evidence.policy=policy;save();
  assert.equal(policy.value.period_blocks,"60");
  assert.equal((await client.reads.token.get_account({account:a.account}))!.value!.recharge_blocks,"144000");check("short-reward-period-keeps-five-day-resource-recharge");
  const vote=async(me:Identity,p:typeof first,direction:number,weight:string)=>client.ops.token.vote({actor:me.account,post_id:p.id,version:p.hash,direction,weight});
  await refuse("free-credits-cannot-vote",[await vote(unfunded,first,1,"1")],unfunded.signer,/paid vote capacity/i);
  await send("upvote-paid-weight",[await vote(a,first,1,"3")],a.signer);
  await send("second-post-upvote",[await vote(c,second,1,"1")],c.signer);
  await send("downvote-paid-weight",[await vote(c,first,2,"1")],c.signer);
  const account=(await client.reads.token.get_account({account:a.account}))!.value!;
  assert.equal(account.free_ticks,"14400000");assert.equal(account.locked,"3");check("votes-use-paid-only-and-lock-used-units");
  await refuse("duplicate-vote-refused",[await vote(a,first,2,"1")],a.signer,/already voted/i);
  await refuse("self-vote-refused",[await vote(b,first,1,"1")],b.signer,/own post/i);
  await refuse("locked-transfer-refused",[await client.ops.token.transfer({from:a.account,to:b.account,value:"18"})],a.signer,/transferable/i);
  const promo={actor:b.account,post_id:first.id,version:first.hash,nonce:"1",slot:0,opportunities:1,burn_amount:"1"};
  await refuse("unapproved-promotion-price-refused",[await client.ops.token.promote({...promo,burn_amount:"2"})],b.signer,/burn amount/i);
  await send("purchase-promotion",[await client.ops.token.promote(promo)],b.signer);
  await refuse("promotion-replay-refused",[await client.ops.token.promote(promo)],b.signer,/active promotion|nonce/i);
  assert.equal((await client.reads.token.get_account({account:b.account}))!.value!.balance,"19");check("promotion-burns-principal");
  await send("cancel-promotion",[await client.ops.token.cancel_promotion({actor:b.account,post_id:first.id,nonce:"1"})],b.signer);
  assert.equal((await client.reads.token.get_promotions({}))!.values[0]!.cancelled,true);check("cancellation-keeps-burn-permanent");
  await refuse("legacy-support-retired",[await client.ops.token.support({actor:a.account,post_id:first.id})],a.signer,/replaced by paid/i);
  const state=await client.reads.token.get_post_economy({post_id:first.id,viewer:a.account});
  assert.equal(state!.reward!.up,"3");assert.equal(state!.reward!.down,"1");
  const end=BigInt(state!.epoch!.end_block);
  if(await head()<end)await refuse("early-settlement-refused",[await client.ops.token.settle_reward({actor:a.account,post_id:first.id})],a.signer,/still open/i);
  await waitBlock(end);
  await send("settle-first-reward",[await client.ops.token.settle_reward({actor:a.account,post_id:first.id})],a.signer);
  await send("settle-second-reward",[await client.ops.token.settle_reward({actor:c.account,post_id:second.id})],c.signer);
  const p1=(await client.reads.token.get_post_economy({post_id:first.id}))!,p2=(await client.reads.token.get_post_economy({post_id:second.id}))!;
  assert.equal(p1.reward!.reward,"72");assert.equal(p2.reward!.reward,"27");
  assert.equal((await client.reads.token.get_account({account:a.account}))!.value!.locked,"3");
  assert.equal((await read("get_economy")).value.reserved,"0");
  assert.equal((await client.reads.token.total_supply({}))!.value,"158");check("exact-allocation-supply-and-no-settlement-refill");
  await refuse("duplicate-settlement-refused",[await client.ops.token.settle_reward({actor:a.account,post_id:first.id})],a.signer,/no unsettled/i);
  evidence.finished=new Date().toISOString();save();console.log(`Completed ${evidence.checks.length} isolated testnet checks. Public token economy was not activated.`);
}catch(error){save();throw error;}
